<?xml version="1.0"?>
<!DOCTYPE employees[

<!ELEMENT employees (employee+)>
<!ELEMENT employee (id,name,email,dob,deptno)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT deptno (#PCDATA)>
]>

<employees>
	<employees>
	<employee>
		<id>1</id>
		<name>Elliot Alderson</name>
		<email>elliot@gmail.com</email>
		<dob>1986-09-17</dob>
		<deptno>ALL SAFE  Cyber Security</deptno>
	</employee>

	<employee>
		<id>2</id>
		<name>Mr. Robot</name>
		<email>mrrobot@gmail.com</email>
		<dob>1960-01-01</dob>
		<deptno>fsociety</deptno>
	</employee>

	<employee>
		<id>3</id>
		<name>Darlene Alderson</name>
		<email>darlene@gmail.com</email>
		<dob>1990-08-09</dob>
		<deptno>fsociety</deptno>
	</employee>

	<employee>
		<id>4</id>
		<name>Angela Moss</name>
		<email>angela.moss@gmail.com</email>
		<dob>1988-11-23</dob>
		<deptno>E Corp</deptno>
	</employee>

	<employee>
		<id>5</id>
		<name>Tyrell Wellick</name>
		<email>tyrell.wellick@gmail.com</email>
		<dob>1984-05-17</dob>
		<deptno>E Corp</deptno>
	</employee>
</employees>






</employees>